version: '{build}'
image: Visual Studio 2022
branches:
  only:
    - master
skip_branch_with_pr: true
build_script:
- cmd: ./build.cmd
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
