<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- <PackageReference Include="Microsoft.CSharp"  /> -->
    <PackageReference Include="NServiceBus" />
    <PackageReference Include="NServiceBus.TransactionalSession" />
    <PackageReference Include="ServiceComposer.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reservations.Data\Reservations.Data.csproj" />
    <ProjectReference Include="..\Reservations.Messages.Commands\Reservations.Messages.Commands.csproj" />
    <ProjectReference Include="..\Reservations.ViewModelComposition.Events\Reservations.ViewModelComposition.Events.csproj" />
    <ProjectReference Include="..\Ticketing.ViewModelComposition.Events\Ticketing.ViewModelComposition.Events.csproj" />
    <ProjectReference Include="..\ITOps.Infrastructure\ITOps.Infrastructure.csproj" />
  </ItemGroup>

</Project>
