<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="NServiceBus" />
    <PackageReference Include="NServiceBus.TransactionalSession" />
    <PackageReference Include="ServiceComposer.AspNetCore"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reservations.ViewModelComposition.Events\Reservations.ViewModelComposition.Events.csproj" />
    <ProjectReference Include="..\Shipping.Data\Shipping.Data.csproj" />
    <ProjectReference Include="..\Shipping.Messages.Commands\Shipping.Messages.Commands.csproj" />
  </ItemGroup>

</Project>
