<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <!-- 🌟 Versions removed to align with Central Package Management -->
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" />
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" />
    <PackageReference Include="Particular.PlatformSample" />
    <PackageReference Include="ServiceComposer.AspNetCore" />
    <PackageReference Include="NServiceBus" />
    <PackageReference Include="NServiceBus.Extensions.Hosting" />
    <PackageReference Include="NServiceBus.TransactionalSession" />
    <PackageReference Include="NServiceBus.Persistence.Sql" />
    <PackageReference Include="NServiceBus.Persistence.Sql.TransactionalSession" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Reservations.ViewModelComposition\Reservations.ViewModelComposition.csproj" />
    <ProjectReference Include="..\Ticketing.ViewModelComposition\Ticketing.ViewModelComposition.csproj" />
    <ProjectReference Include="..\Finance.ViewModelComposition\Finance.ViewModelComposition.csproj" />
    <ProjectReference Include="..\AspireDemo.ServiceDefaults\AspireDemo.ServiceDefaults.csproj" />
    <ProjectReference Include="..\ITOps.Infrastructure\ITOps.Infrastructure.csproj" />
    <ProjectReference Include="..\Shipping.ViewModelComposition\Shipping.ViewModelComposition.csproj" />
   
  </ItemGroup> 

  <ItemGroup>
    <Folder Include="wwwroot\lib\bootstrap\dist\css\" />
    <Folder Include="wwwroot\lib\bootstrap\dist\js\" />
    <Folder Include="wwwroot\lib\jquery\dist\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\_ViewImports.cshtml">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
